$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
language: en
ignoreRegExpList:
  - Email
  - /@[^\s]*/g
words:
  - actionbar
  - aftersign
  - agoraflat
  - aliyun
  - amannn
  - antd
  - anticon
  - apidae
  - apng
  - appleid
  - APPLEIDPASS
  - applinks
  - Appstore
  - APPVERSION
  - autodocs
  - autohiding
  - autorun
  - Autowired
  - avif
  - blockmap
  - bokeh
  - bootup
  - borderless
  - browserslist
  - btns
  - btrfs
  - byteranges
  - changelogen
  - Cheerego
  - chunkhash
  - cjvf
  - CLASSNAME
  - Clav
  - clazz
  - clsx
  - Codepen
  - commitlint
  - commitlintrc
  - copydir
  - corepack
  - cppzst
  - crimx
  - cruciferae
  - csstype
  - ctrlcmd
  - customizational
  - czvf
  - dataurl
  - dbaeumer
  - dgrijalva/jwt-go
  - DOCKERHUB
  - dockerignore
  - dockerode
  - dont
  - dynamodbattribute
  - echat
  - EDITMSG
  - electronjs
  - emittery
  - esbuild
  - eslintignore
  - estree
  - felidae
  - flac
  - flowconfig
  - Frameless
  - fullname
  - fullscreenable
  - GOARCH
  - gonic
  - GOOS
  - gvproxy
  - hprof
  - hyrious
  - icns
  - iconify
  - iife
  - Impls
  - importlib
  - isstring
  - jiti
  - jsonforms
  - kaitian
  - keymaps
  - keystyle
  - keytar
  - kticon
  - Kube
  - kubeconfig
  - kubernetes
  - languagedetector
  - ldflags
  - linebreak
  - lintstagedrc
  - Lngs
  - lukeed
  - maximizable
  - metafile
  - micromessenger
  - Minikube
  - minlength
  - monokai
  - Moskize
  - Mountpoint
  - multipass
  - napi
  - nightlies
  - nindent
  - nodesselection
  - nodrag
  - NOKQUEUE
  - nonoctal
  - nopan
  - notarytool
  - nowheel
  - npmrc
  - nrwl
  - nsis
  - oomol
  - OOMOLI
  - openai
  - opensumi
  - Opentrs
  - orchidaceae
  - osascript
  - outfile
  - patrickmn
  - pbcopy
  - pino
  - pnpm
  - podman
  - preinstall
  - preship
  - projectnode
  - pycache
  - qcow
  - qrcode
  - Quan
  - reactflow
  - regx
  - rejt
  - repr
  - respawn
  - ripgrep
  - rjsf
  - rmvb
  - rootfs
  - runtimes
  - scpt
  - sergeysova
  - signin
  - signout
  - signup
  - spdlog
  - subflow
  - submenu
  - Sumi
  - svglint
  - tabbar
  - taozeyu
  - tinycolor
  - titlebar
  - togglefullscreen
  - tolerations
  - topbar
  - treeshake
  - tsup
  - typecheck
  - tzst
  - uischema
  - uischemas
  - unbzip
  - uncategorized
  - uncompression
  - unexpect
  - unhide
  - unmaximize
  - unocss
  - untar
  - unzst
  - updown
  - uuidv
  - Variatio
  - vertx
  - vfkit
  - videojs
  - viewports
  - vite
  - vitejs
  - vitepress
  - vocana
  - webfonts
  - webm
  - webp
  - webstorm
  - wechat
  - wopjs
  - xproj
  - yalc
  - yarnrc
  - Zeyu
  - zindex
dictionaries:
  - companies
  - softwareTerms
  - misc
  - typescript
  - node
  - rust
  - golang
  - html
  - css
  - bash
  - docker
  - fonts
  - filetypes
  - npm
  - fullstack
  - en_US
  - en-gb
flagWords:
  - fuck
  - bitch
  - asshole
  - bullshit
  - crap
  - suck
  - wtf
  - idiot
  - moron
  - asshole
  - bastard
  - jerk
  - jerkoff
  - douche
  - dickhead
  - douchebag
  - cunt
  - nigger
  - chink
  - spic
  - kike
  - fag
  - wetback
  - piss
  - damn
ignorePaths:
  - "**/coverage/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml
  - CHANGELOG.md
  - "**/CHANGELOG.md"
  - cspell.config.yml
  - .vscode/**
